/******************** system config ********************/
/* soc config */
#define CONFIG_SOC "tai"
#define CONFIG_SOC_SPICACHE_PROFILE 1
#define CONFIG_SOC_SERIES "tai"
#define CONFIG_BOARD_TAI_EVB 1
#define CONFIG_SOC_SERIES_TAI 1
#define CONFIG_CPU_HAS_ARM_MPU 1
#define CONFIG_HAS_SWO 1
#define CONFIG_SOC_FAMILY_ACTS 1
#define CONFIG_SOC_FAMILY "actions"
#define CONFIG_SOC_SPI0_USE_CK64M 1
#define CONFIG_SOC_TAI 1
#define CONFIG_ACTS_DEDICATED_MEMORY 1
#define CONFIG_SOC_LOG_LEVEL_INF 1
#define CONFIG_SOC_LOG_LEVEL 3

/* arch config */
#define CONFIG_ARCH "arm"
#define CONFIG_CPU_CORTEX 1
#define CONFIG_CPU_CORTEX_M 1
#define CONFIG_ISA_THUMB2 1
#define CONFIG_ASSEMBLER_ISA_THUMB2 1
#define CONFIG_COMPILER_ISA_THUMB2 1
#define CONFIG_STACK_ALIGN_DOUBLE_WORD 1
#define CONFIG_FAULT_DUMP 2
#define CONFIG_ARM_UNWIND 1
#define CONFIG_CPU_CORTEX_M4 1
#define CONFIG_CPU_CORTEX_M_HAS_SYSTICK 1
#define CONFIG_CPU_CORTEX_M_HAS_DWT 1
#define CONFIG_CPU_CORTEX_M_HAS_BASEPRI 1
#define CONFIG_CPU_CORTEX_M_HAS_VTOR 1
#define CONFIG_CPU_CORTEX_M_HAS_PROGRAMMABLE_FAULT_PRIOS 1
#define CONFIG_ARMV7_M_ARMV8_M_MAINLINE 1
#define CONFIG_GEN_ISR_TABLES 1
#define CONFIG_TEST_EXTRA_STACKSIZE 0
#define CONFIG_ARM_MPU_REGION_MIN_ALIGN_AND_SIZE 4
#define CONFIG_GEN_IRQ_VECTOR_TABLE 1
#define CONFIG_MAIN_STACK_SIZE 1024
#define CONFIG_IDLE_STACK_SIZE 400
#define CONFIG_ISR_STACK_SIZE 768
#define CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE 900
#define CONFIG_ARM 1
#define CONFIG_ARCH_IS_SET 1
#define CONFIG_ARCH_LOG_LEVEL_INF 1
#define CONFIG_ARCH_LOG_LEVEL 3
#define CONFIG_MPU_LOG_LEVEL_INF 1
#define CONFIG_MPU_LOG_LEVEL 3
#define CONFIG_GEN_PRIV_STACKS 1
#define CONFIG_NUM_IRQS 32
#define CONFIG_GEN_SW_ISR_TABLE 1
#define CONFIG_ARCH_SW_ISR_TABLE_ALIGN 0
#define CONFIG_GEN_IRQ_START_VECTOR 0
#define CONFIG_ARCH_HAS_TIMING_FUNCTIONS 1
#define CONFIG_ARCH_HAS_RAMFUNC_SUPPORT 1
#define CONFIG_ARCH_HAS_NESTED_EXCEPTION_DETECTION 1
#define CONFIG_ARCH_SUPPORTS_COREDUMP 1
#define CONFIG_ARCH_SUPPORTS_ARCH_HW_INIT 1
#define CONFIG_ARCH_HAS_EXTRA_EXCEPTION_INFO 1
#define CONFIG_ARCH_HAS_THREAD_LOCAL_STORAGE 1
#define CONFIG_ARCH_HAS_THREAD_ABORT 1
#define CONFIG_CPU_HAS_MPU 1
#define CONFIG_TEST_ARM_CORTEX_M 1
#define CONFIG_HAS_CMSIS_CORE 1
#define CONFIG_HAS_CMSIS_CORE_M 1

/* kernel config */
#define CONFIG_KERNEL_LOG_LEVEL_INF 1
#define CONFIG_KERNEL_LOG_LEVEL 3
#define CONFIG_MULTITHREADING 1
#define CONFIG_NUM_COOP_PRIORITIES 16
#define CONFIG_NUM_PREEMPT_PRIORITIES 15
#define CONFIG_MAIN_THREAD_PRIORITY 0
#define CONFIG_COOP_ENABLED 1
#define CONFIG_PREEMPT_ENABLED 1
#define CONFIG_PRIORITY_CEILING 0
#define CONFIG_NUM_METAIRQ_PRIORITIES 0
#define CONFIG_ERRNO 1
#define CONFIG_SCHED_DUMB 1
#define CONFIG_WAITQ_DUMB 1
#define CONFIG_BOOT_BANNER 1
#define CONFIG_BOOT_DELAY 0
#define CONFIG_ATOMIC_OPERATIONS_BUILTIN 1
#define CONFIG_TIMESLICING 1
#define CONFIG_TIMESLICE_SIZE 0
#define CONFIG_TIMESLICE_PRIORITY 0
#define CONFIG_POLL 1
#define CONFIG_NUM_MBOX_ASYNC_MSGS 10
#define CONFIG_NUM_PIPE_ASYNC_MSGS 10
#define CONFIG_KERNEL_MEM_POOL 1
#define CONFIG_HEAP_MEM_POOL_SIZE 0
#define CONFIG_ARCH_HAS_CUSTOM_SWAP_TO_MAIN 1
#define CONFIG_SWAP_NONATOMIC 1
#define CONFIG_SYS_CLOCK_EXISTS 1
#define CONFIG_TIMEOUT_64BIT 1
#define CONFIG_XIP 1
#define CONFIG_KERNEL_INIT_PRIORITY_OBJECTS 30
#define CONFIG_KERNEL_INIT_PRIORITY_DEFAULT 40
#define CONFIG_KERNEL_INIT_PRIORITY_DEVICE 50
#define CONFIG_APPLICATION_INIT_PRIORITY 90
#define CONFIG_MP_NUM_CPUS 1
#define CONFIG_TICKLESS_IDLE 1
#define CONFIG_TICKLESS_IDLE_THRESH 3
#define CONFIG_TICKLESS_KERNEL 1
#define CONFIG_HAS_DTS 1
#define CONFIG_HAS_DTS_GPIO 1
#define CONFIG_INIT_STACKS 1
#define CONFIG_SYSTEM_WORKQUEUE_PRIORITY -1
#define CONFIG_SYSTEM_CLOCK_INIT_PRIORITY 0
#define CONFIG_TICKLESS_CAPABLE 1
#define CONFIG_THREAD_NAME 1
#define CONFIG_THREAD_MAX_NAME_LEN 32
#define CONFIG_THREAD_MONITOR 1
#define CONFIG_THREAD_STACK_INFO 1
#define CONFIG_KERNEL_SHOW_STACK 1
#define CONFIG_KERNEL_ENTRY "__start"
#define CONFIG_KERNEL_BIN_NAME "zephyr"
#define CONFIG_MAX_TIMER_COUNT 5

/* lib config */
#define CONFIG_MINIMAL_LIBC 1
#define CONFIG_HAS_NEWLIB_LIBC_NANO 1
#define CONFIG_MINIMAL_LIBC_MALLOC 1
#define CONFIG_MINIMAL_LIBC_MALLOC_ARENA_SIZE 0
#define CONFIG_MINIMAL_LIBC_CALLOC 1
#define CONFIG_MINIMAL_LIBC_REALLOCARRAY 1
#define CONFIG_STDOUT_CONSOLE 1
#define CONFIG_SYS_HEAP_ALLOC_LOOPS 3
#define CONFIG_CBPRINTF_COMPLETE 1
#define CONFIG_CBPRINTF_FULL_INTEGRAL 1
#define CONFIG_CBPRINTF_N_SPECIFIER 1
#define CONFIG_POSIX_MAX_FDS 4
#define CONFIG_RBUF_LIB 1

/* tinycrypt config */
#define CONFIG_TINYCRYPT 1
#define CONFIG_TINYCRYPT_SHA256 1
#define CONFIG_TINYCRYPT_SHA256_HMAC 1
#define CONFIG_TINYCRYPT_SHA256_HMAC_PRNG 1
#define CONFIG_TINYCRYPT_AES 1
#define CONFIG_TINYCRYPT_AES_CMAC 1

/* compile config */
#define CONFIG_PARTITION 1
#define CONFIG_FIRMWARE_VERSION 1
#define CONFIG_TOOLCHAIN_GNUARMEMB 1
#define CONFIG_LINKER_ORPHAN_SECTION_WARN 1
#define CONFIG_HAS_FLASH_LOAD_OFFSET 1
#define CONFIG_USE_DT_CODE_PARTITION 1
#define CONFIG_SRAM_SIZE 38
#define CONFIG_SRAM_EXTRA_SIZE 0x180
#define CONFIG_SRAM_TOTAL_SIZE 40
#define CONFIG_SRAM_BASE_ADDRESS 0x100000
#define CONFIG_FLASH_SIZE 4096
#define CONFIG_FLASH_BASE_ADDRESS 0x1000000
#define CONFIG_FLASH_LOAD_OFFSET 0x100000
#define CONFIG_FLASH_LOAD_SIZE 0x100000
#define CONFIG_LINKER_SORT_BY_ALIGNMENT 1
#define CONFIG_SIZE_OPTIMIZATIONS 1
#define CONFIG_COMPILER_OPT ""
#define CONFIG_RUNTIME_ERROR_CHECKS 1
#define CONFIG_OUTPUT_STAT 1
#define CONFIG_OUTPUT_DISASSEMBLY 1
#define CONFIG_OUTPUT_PRINT_MEMORY_USAGE 1
#define CONFIG_BUILD_OUTPUT_HEX 1
#define CONFIG_BUILD_OUTPUT_BIN 1
#define CONFIG_DEPRECATED_ZEPHYR_INT_TYPES 1
#define CONFIG_COMPAT_INCLUDES 1
#define CONFIG_ROM_START_OFFSET 0x0


/******************** driver config ********************/
/* gpio config */
#define CONFIG_GPIO 1
#define CONFIG_GPIO_LOG_LEVEL_INF 1
#define CONFIG_GPIO_LOG_LEVEL 3
#define CONFIG_GPIO_ACTS 1
#define CONFIG_GPIO_ACTS_DEV_NAME "GPIOA"

/* spi config */
#define CONFIG_SPI 1
#define CONFIG_SPI_INIT_PRIORITY 70
#define CONFIG_SPI_COMPLETION_TIMEOUT_TOLERANCE 200
#define CONFIG_SPI_LOG_LEVEL_INF 1
#define CONFIG_SPI_LOG_LEVEL 3
#define CONFIG_SPI_ACTS 1
#define CONFIG_SPI_HOST 3
/**
 * SPIx clock source configuration.
 *   - 0: RC64M
 *   - 1: HOSC(24MHz)
 */
#define CONFIG_SPI0_CLK_SOURCE          0
#define CONFIG_SPI2_CLK_SOURCE          0
#define CONFIG_SPI3_CLK_SOURCE          0

/* flash config */
#define CONFIG_FLASH_HAS_DRIVER_ENABLED 1
#define CONFIG_FLASH_HAS_PAGE_LAYOUT 1
#define CONFIG_FLASH 1
#define CONFIG_FLASH_LOG_LEVEL_INF 1
#define CONFIG_FLASH_LOG_LEVEL 3
#define CONFIG_FLASH_PAGE_LAYOUT 1
#define CONFIG_XSPI_NOR_ACTS_DEV_TEST_DELAYCHAIN_PRIORITY 60
#define CONFIG_SPI_FLASH_ACTS 1

/* dma config */
#define CONFIG_DMA 1
#define CONFIG_DMA_0_NAME "DMA_0"
#define CONFIG_DMA_0_IRQ_PRI 3
#define CONFIG_DMA_1_NAME "DMA_1"
#define CONFIG_DMA_2_NAME "DMA_2"
#define CONFIG_DMA_LOG_LEVEL_INF 1
#define CONFIG_DMA_LOG_LEVEL 3
#define CONFIG_DMA_ACTS 1
#define CONFIG_VDMA_ACTS 1
#define CONFIG_DMA_DBG_DUMP 1
#define CONFIG_DMA_LCD_RESEVER_CHAN 12
#define CONFIG_DMA_SPINAND_RESEVER_CHAN 12
#define CONFIG_SYS_LOG_USB_OTG_DRIVER_LEVEL 0

/* audio config */
#define CONFIG_AUDIO_ACTS 1
#define CONFIG_AUDIO_IN_ACTS 1
#define CONFIG_AUDIO_IN_ACTS_DEV_NAME "audio_in"
#define CONFIG_AUDIO_IN_ADC_SUPPORT 1
#define CONFIG_ADC_STARTUP_DISCARD_TIME 20
#define CONFIG_AUDIO_CHAN_SEL_INIT_PRIORITY 60

/* nvram config */
#define CONFIG_NVRAM_CONFIG 1
#define CONFIG_NVRAM_STORAGE_FLASH 1
#define CONFIG_NVRAM_STORAGE_DEV_NAME "spinor"
#define CONFIG_NVRAM_FACTORY_REGION_SIZE 0x2000
#define CONFIG_NVRAM_FACTORY_RW_REGION_SIZE 0x2000
#define CONFIG_NVRAM_USER_REGION_SIZE 0x4000
#define CONFIG_NVRAM_FACTORY_REGION_SEGMENT_SIZE 0x1000
#define CONFIG_NVRAM_FACTORY_RW_REGION_SEGMENT_SIZE 0x1000
#define CONFIG_NVRAM_USER_REGION_SEGMENT_SIZE 0x1000
#define CONFIG_NVRAM_CONFIG_INIT_PRIORITY 48

/* input dev config */
#define CONFIG_INPUT_DEV 1
#define CONFIG_SYS_LOG_INPUT_DEV_LEVEL 0
#define CONFIG_INPUT_DEV_ACTS_KEY_PAD 1
#define CONFIG_INPUT_DEV_ACTS_IR_CAPTURE 1

/* power supply config */
#define CONFIG_POWER_SUPPLY 1
#define CONFIG_ACTS_BATTERY_DEV_NAME "batadc"
#define CONFIG_ACTS_BATTERY_SUPPLY_DRY_CELL 1

/* sensor-temperature config */
#define CONFIG_SENSOR    0
#define CONFIG_ACTS_SENSOR_DEV_NAME "sensadc"
#define CONFIG_SENSOR_AUTO_CMPEN     0

/* power manager config */
#define CONFIG_PM 1
//#define CONFIG_PM_DIRECT_FORCE_MODE 1
//#define CONFIG_PM_ENHANCE_S3VDDRET_VOL 1
#define CONFIG_PM_POLICY_APP 1
#define CONFIG_PM_LOG_LEVEL_INF 1
#define CONFIG_PM_LOG_LEVEL 3
#define CONFIG_PM_DEVICE 1
#define CONFIG_DEVICE_POWER_MANAGEMENT 1
#define CONFIG_PM_MAX_DEVICES 15

/* clock config */
#define CONFIG_ACTS_TIMER 1
#define CONFIG_HOSC_CLK_MHZ 24
#define CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC 6000000
#define CONFIG_SYS_CLOCK_TICKS_PER_SEC 500

/* spi flash config */
#define CONFIG_SPI_FLASH_NAME      		"spi_flash"
#define CONFIG_SPI_FLASH_CHIP_SIZE      0x80000
#define CONFIG_SPI_FLASH_BUS_WIDTH      2
#define CONFIG_SPI_FLASH_DELAY_CHAIN    8
#define CONFIG_SPI_FLASH_CLK_HZ         48000000
#define CONFIG_SPI_FLASH_NXIO_ENABLE    0

/* bt driver config */
#define CONFIG_BT_DRV 1
#define CONFIG_BT_HCI_RX_PRIO 6
#define CONFIG_BT_HCI_RX_STACK_SIZE 400
#define CONFIG_BT_HCI_TX_RBUF_SIZE 512
#define CONFIG_BT_HCI_RX_RBUF_SIZE 512
#define CONFIG_BT_HCI_ACTS 1
#define CONFIG_BT_RBUF_DUMP 1
#define CONFIG_BT_HCI_TX_PRINT 1
#define CONFIG_BT_HCI_RX_PRINT 1

/* bt cpu config */
#define CONFIG_IPMSG_ACTS 1
#define CONFIG_IPMSG_ACTS_BTC 1
#define CONFIG_BTC_NAME "BTC"
#define CONFIG_BTC_IRQ0_PRI 0
#define CONFIG_BTC_IRQ1_PRI 0

/* uart config */
#define CONFIG_UART_INTERRUPT_DRIVEN 1

#define CONFIG_UART_0           1
#define CONFIG_UART_0_NAME      "UART_0"
#define CONFIG_UART_0_IRQ_PRI   0
#define CONFIG_UART_0_SPEED     3000000
#define CONFIG_UART_0_USE_TX_DMA   1
#define CONFIG_UART_0_TX_DMA_CHAN  0x0
#define CONFIG_UART_0_TX_DMA_ID    1
#define CONFIG_UART_1           1
#define CONFIG_UART_1_NAME      "UART_1"
#define CONFIG_UART_1_IRQ_PRI   0
#define CONFIG_UART_1_SPEED     115200
#define CONFIG_UART_1_USE_TX_DMA   0
#define CONFIG_UART_1_TX_DMA_CHAN  0xff
#define CONFIG_UART_1_TX_DMA_ID    2
#define CONFIG_UART_2           0
#define CONFIG_UART_2_NAME      "UART_2"
#define CONFIG_UART_2_IRQ_PRI   0
#define CONFIG_UART_2_SPEED     115200
#define CONFIG_UART_2_USE_TX_DMA   0
#define CONFIG_UART_2_TX_DMA_CHAN  0xff
#define CONFIG_UART_2_TX_DMA_ID    2
#define CONFIG_UART_3           0
#define CONFIG_UART_4           0

/* console config */
#define CONFIG_PRINTK 1
#define CONFIG_EARLY_CONSOLE 1
#define CONFIG_UART_CONSOLE_ON_DEV_NAME "UART_0"
#define CONFIG_CONSOLE 1
#define CONFIG_CONSOLE_INPUT_MAX_LINE_LEN 128
#define CONFIG_CONSOLE_HAS_DRIVER 1
#define CONFIG_UART_CONSOLE 1
#define CONFIG_UART_CONSOLE_INIT_PRIORITY 60
#define CONFIG_UART_CONSOLE_LOG_LEVEL_INF 1
#define CONFIG_UART_CONSOLE_LOG_LEVEL 3

/* audio adc config */
/* AUDIO ADC device compatible name */
#define CONFIG_AUDIO_ADC_0_NAME                 "ADC_0"
/* AUDIO ADC interrupt priority */
#define CONFIG_AUDIO_ADC_0_IRQ_PRI              (0)
/* The DMA channel for ADC FIFO0  */
#define CONFIG_AUDIO_ADC_0_FIFO0_DMA_CHAN       (0xff)
/* The DMA slot ID for ADC FIFO0 */
#define CONFIG_AUDIO_ADC_0_FIFO0_DMA_ID         (0xc)
/* ADC channel0 frequency which range from 0 ~ 111111b. */
#define CONFIG_AUDIO_ADC_0_CH0_FREQUENCY        (0)
/* If 1 to enable ADC channel0 HPF high frequency range. */
#define CONFIG_AUDIO_ADC_0_CH0_HPF_FC_HIGH      (1)
/*
 * Audio VMIC control MIC power as <vmic-ctl0, vmic-ctl1, vmic-ctl2>.
 *   - 0x: disable VMIC OP
 *   - 2: bypass VMIC OP
 *   - 3: enable VMIC OP
 */
#define CONFIG_AUDIO_ADC_0_VMIC_CTL_ARRAY       {3}
/**
 * Audio VMIC control the MIC voltage as <vmic-vol0, vmic-vol1>.
 *   - 0: 1.7 * REF
 *   - 1: 1.8 * REF
 *   - 2: 1.9 * REF
 *   - 3: 2 * REF
 */
#define CONFIG_AUDIO_ADC_0_VMIC_VOLTAGE_ARRAY   {2}
/* @brief The macro to define an audio device */
#define AUDIO_ANALOG_MIC0 (AUDIO_DEV_TYPE_AMIC | 0)
#define AUDIO_DIGITAL_MIC0 (AUDIO_DEV_TYPE_DMIC | 0)
#define BOARD_AUDIO_INPUT_MAP       {AUDIO_ANALOG_MIC0, ADC_CH_INPUT0NP_DIFF},\
									{AUDIO_DIGITAL_MIC0, ADC_CH_DMIC},

/* pwm config */
#define CONFIG_PWM           1
#define CONFIG_PWM_NAME      "PWM"
#define CONFIG_PWM_CHANS     9
#define CONFIG_PWM_CYCLE     8000
#define CONFIG_PWM_USE_DMA   1
#define CONFIG_PWM_DMA_CHAN  0xff
#define CONFIG_PWM_DMA_ID    13
#define CONFIG_PWM_IRQ_PRI   0
#define CONFIG_LOG_PWM_DEV_LEVEL 0
#define CONFIG_PWM_TAI_ACTS 1

/* keypad config */
#define CONFIG_KEYPAD           1
#define CONFIG_KEYPAD_REG       0
#define CONFIG_KEYPAD_NAME      "keypad"
#define CONFIG_KEYPAD_PENM      0xeb8f
#define CONFIG_KEYPAD_KMS       1
#define CONFIG_KEYPAD_IRQ_PRI   0

/* capture board cfg */
#define CONFIG_CAPTURE           1
#define CONFIG_CAPTURE_NAME      "capture"
#define CONFIG_CAPTURE_IRQ_PRI   0

/* lpcmp cfg */
#define CONFIG_LPCMP           1
#define CONFIG_LPCMP_NAME      "lpcmp"
#define CONFIG_LPCMP_IRQ_PRI   0
#define CONFIG_LPCMP_INIT_PRIORITY 50

/* rc32k calibration */
#define CONFIG_RC32K_CALIB     1
#define CONFIG_RC32K_CALIB_LEV 11

/* standby config */
#define CONFIG_STANDBY_POLL_DELAY_WORK
#ifdef CONFIG_STANDBY_POLL_DELAY_WORK
//#define CONFIG_STANDBY_HANDLE_IN_DELAY_WORK
#endif
/* The threshold of the latest timer to enter standby */
#define CONFIG_STANDBY_THRESHOLD_MSEC 30
/* system idle time to auto enter standby */
#define CONFIG_AUTO_STANDBY_TIME_MSEC 30
/* system idle time to power off */
#define CONFIG_AUTO_POWEDOWN_TIME_SEC 0
/* low power to power off */
#define CONFIG_LOW_POWER_POWERDOWN	1
/* sleep wake up source enumation
 *
 * struct sleep_wk_src_t {
 *	 uint8_t is_en;
 *	 uint8_t irq_id;
 * };
 */
#define SLEEP_WAKE_SRC_LPCMP       {1, IRQ_ID_LPCMP}
#define SLEEP_WAKE_SRC_BT1       {1, IRQ_ID_BTCPU1}
#define SLEEP_WAKE_SRC_BT       {1, IRQ_ID_BTCPU0}
#define SLEEP_WAKE_SRC_GPIO     {0, IRQ_ID_GPIO}
#define SLEEP_WAKE_SRC_RTC_CMP0 {1, IRQ_ID_CMP0}
#define SLEEP_WAKE_SRC_KEY      {1, IRQ_ID_KEY}
/* PMU sleep wake up source list */
#define CONFIG_SLEEP_WAKE_SRC_LIST  {SLEEP_WAKE_SRC_LPCMP, SLEEP_WAKE_SRC_BT1, SLEEP_WAKE_SRC_BT, SLEEP_WAKE_SRC_GPIO, SLEEP_WAKE_SRC_RTC_CMP0, SLEEP_WAKE_SRC_KEY}

#define CONFIG_SW_S5_WAKE_SRC_LIST  {SLEEP_WAKE_SRC_LPCMP}

#define CONFIG_WAKEUP_RTC_CMP0_TICKS 0 //30
#define CONFIG_RAMPWR_CTL_MAIN_DOMAIN            ((0x3 << 20) | (0x3 << 24))
#define CONFIG_RAMPWR_CTL_BT_DOMAIN              ((0x3 << 26) | (0x1 << 30))
#define CONFIG_RAMPWR_CTL_RETENTION_MASK         (0xA0A) //(0xAAAAAAAA)
#define CONFIG_RAMPWR_SET_RETENTION              (0x0020aa0a) //(0xAFA) (0x002FAAFA)

//#define CONFIG_JTAG_MFP_SW_EN 1

/*
 * handler of non_retention RAM before and after deepsleep
 * 0----no operation
 * 1----Reclaim unused space in the stack, then move bss in non retention ram to unused retention ram space.
				Note: Reclaim space is not determined
 * 2----move bss in non retention ram to unused retention ram space.
				NOTE:The retention RAM space of backup BSS is determined
*/
#define DEEPSLEEP_MODE 2

#define CONFIG_DEEPSLEEP_LOG_LEVEL 3

/******************** framework config ********************/
/* bt stack config */
#define CONFIG_BT 1
#define CONFIG_BT_LOG_LEVEL_INF 1
#define CONFIG_BT_LOG_LEVEL 3
#define CONFIG_BT_HCI 1
//#define CONFIG_BT_DEBUG_LOG 1
//#define CONFIG_BT_DEBUG_ATT 1
#define CONFIG_BT_PERIPHERAL 1
#define CONFIG_BT_BROADCASTER 1
#define CONFIG_BT_CONN 1
#define CONFIG_BT_MAX_CONN 1
#define CONFIG_BT_MAX_PAIRED 1
#define CONFIG_BT_DEVICE_NAME "BLE RMC"
#define CONFIG_BT_RX_BUF_COUNT 2
#define CONFIG_BT_RX_BUF_LEN 73
//#define CONFIG_BT_WHITELIST 1
#define CONFIG_BT_L2CAP_RX_MTU 65
#define CONFIG_BT_L2CAP_TX_BUF_COUNT 2
#define CONFIG_BT_L2CAP_TX_FRAG_COUNT 1
#define CONFIG_BT_L2CAP_TX_MTU 65
#define CONFIG_BT_GAP_AUTO_UPDATE_CONN_PARAMS 1
//#define CONFIG_BT_GAP_PERIPHERAL_PREF_PARAMS 1
#define CONFIG_BT_PERIPHERAL_PREF_MIN_INT 24
#define CONFIG_BT_PERIPHERAL_PREF_MAX_INT 40
#define CONFIG_BT_PERIPHERAL_PREF_SLAVE_LATENCY 0
#define CONFIG_BT_PERIPHERAL_PREF_TIMEOUT 42
#define CONFIG_BT_CONN_PARAM_UPDATE_TIMEOUT 5000
#define CONFIG_BT_PHY_UPDATE 1
//#define CONFIG_BT_DATA_LEN_UPDATE 1
#define CONFIG_BT_RPA 1
#define CONFIG_BT_ASSERT 1
#define CONFIG_BT_ASSERT_VERBOSE 1
#define CONFIG_BT_DEBUG 1
#define CONFIG_BT_HCI_HOST 1
#define CONFIG_BT_HCI_CMD_COUNT 2
#define CONFIG_BT_DISCARDABLE_BUF_SIZE 45
#define CONFIG_BT_HCI_TX_STACK_SIZE 768
#define CONFIG_BT_HCI_ECC_STACK_SIZE 1100
#define CONFIG_BT_HCI_TX_PRIO 7
#define CONFIG_BT_HCI_RESERVE 0
#define CONFIG_BT_RX_STACK_SIZE 1024
#define CONFIG_BT_RX_PRIO 8
#define CONFIG_BT_DRIVER_RX_HIGH_PRIO 6
#define CONFIG_BT_HOST_CRYPTO 1
#define CONFIG_BT_SETTINGS 1
#define CONFIG_BT_CONN_TX_MAX 1
//#define CONFIG_BT_AUTO_DATA_LEN_UPDATE 1
#define CONFIG_BT_SMP 1
#define CONFIG_BT_BONDABLE 1
#define CONFIG_BT_SMP_ENFORCE_MITM 1
#define CONFIG_BT_ATT_PREPARE_COUNT 0
#define CONFIG_BT_GATT_SERVICE_CHANGED 1
#define CONFIG_BT_GATT_CACHING 1
#define CONFIG_BT_GATT_CLIENT 1
#define CONFIG_BT_GATT_READ_MULTIPLE 1
#define CONFIG_BT_CREATE_CONN_TIMEOUT 3
#define CONFIG_BT_DEVICE_APPEARANCE 0
#define CONFIG_BT_ID_MAX 1
#define CONFIG_BT_ECC 1
#define CONFIG_BT_COMPANY_ID 0x05F1
#define CONFIG_BT_SETTINGS_CCC_LAZY_LOADING 1
#define CONFIG_BT_SETTINGS_USE_PRINTK 1
#define CONFIG_BT_SMP_ALLOW_UNAUTH_OVERWRITE 1
#define CONFIG_BT_KEYS_OVERWRITE_OLDEST 1

/* log config */
#define CONFIG_LOG 1
#define CONFIG_LOG_MODE_MINIMAL 1
#define CONFIG_LOG_MINIMAL 1
#define CONFIG_LOG_DEFAULT_LEVEL 3
#define CONFIG_LOG_OVERRIDE_LEVEL 0
#define CONFIG_LOG_MAX_LEVEL 4
#define CONFIG_ASSERT_VERBOSE 1
#define CONFIG_LOG_BUFFER_SIZE 4096

/* net buf config */
#define CONFIG_NET_BUF 1
#define CONFIG_NET_BUF_USER_DATA_SIZE 4
#define CONFIG_NET_BUF_LOG_LEVEL_INF 1
#define CONFIG_NET_BUF_LOG_LEVEL 3
#define CONFIG_SYS_POWER_MANAGEMENT 1

/* settings config */
#define CONFIG_SETTINGS 1
#define CONFIG_SETTINGS_LOG_LEVEL_INF 1
#define CONFIG_SETTINGS_LOG_LEVEL 3
#define CONFIG_SETTINGS_DYNAMIC_HANDLERS 1
#define CONFIG_SETTINGS_NVRAM 1

/* sdfs config */
#define CONFIG_SD_FS 1
#define CONFIG_SD_FS_VADDR_START 0x1800000
#define CONFIG_SD_FILE_MAX 1

/******************** app config ********************/
#include "autoconf_app.h"
